### ISSUE TITLE
Returned null if value contains &

### ISSUE THREAD

**Issue by k-rustemuly** [CrazyTapok-bit/tgWebValid#73]
https://github.com/CrazyTapok-bit/tgWebValid/blob/a0df09270c63db98aa5c70ffea29d0f541c4493a/src/Make/Make.php#L55

**Comment by CrazyTapok-bit** [comment]
Hello
Please specify the version of the package you are using, what type of validation you are invoking, and the data you are validating. So that I can do a full check and find the problem.

If the data contains personal information, you can delete it by replacing it with other text

**Comment by k-rustemuly** [comment]
Hi.
v4.1.0
php 8.1.27

**Comment by k-rustemuly** [comment]
query_id=AAG25pdlAgAAALbml2U7ocxX&user=%7B%22id%22%3A5999421110%2C%22first_name%22%3A%22Fast%20%26%20Furious%22%2C%22last_name%22%3A%22%22%2C%22username%22%3A%22furious_fast7%22%2C%22language_code%22%3A%22ru%22%2C%22allows_write_to_pm%22%3Atrue%7D&auth_date=1713355111&hash=9f8fb0493f596e2806292d8f2afde3ab4aae678c20c5000d0181ff5a0ac79138

**Comment by CrazyTapok-bit** [comment]
So, I found the reason for this behavior. It's all about the `&` symbol used in the `Fast & Furious` username. This is because this symbol is used to divide data into parts. And after its division, in this case json comes out truncated, and accordingly gives an error

It is necessary to think how it can be corrected, leaving the data intact

https://github.com/CrazyTapok-bit/tgWebValid/blob/a0df09270c63db98aa5c70ffea29d0f541c4493a/src/Validator/InitDataValidator.php#L36

**Comment by CrazyTapok-bit** [comment]
Maybe you have some ideas? I will be glad to receive your pull request)

**Comment by CrazyTapok-bit** [comment]
@k-rustemuly The bug is fixed, please update to [v4.2.2](https://github.com/CrazyTapok-bit/tgWebValid/releases/tag/v4.2.2)

**Comment by k-rustemuly** [comment]
thanks
