### ISSUE TITLE
Add #standWithPalestine label to readme

### ISSUE THREAD

**Issue by weidali** [CrazyTapok-bit/tgWebValid#75]
I saw than repo has #stantWithUkraina flag. 
For a more comprehensive approach, it’s necessary to add #standWithPalestine flag.

**Comment by CrazyTapok-bit** [comment]
Hello
Thank you for your attention to our project

We support Ukraine because russia has attacked us and is waging an open, aggressive, bloody and simply beastly full-scale war against us. Destroying civilians, children, schools, kindergartens and all living things around. But we continue to fight and destroy the occupier

**Comment by weidali** [comment]
> Hello Thank you for your attention to our project
> 
> We support Ukraine because russia has attacked us and is waging an open, aggressive, bloody and simply beastly full-scale war against us. Destroying civilians, children, schools, kindergartens and all living things around. But we continue to fight and destroy the occupier

You shouldn't be so egoistic. 
Because Israel has attacked Palestine like you and  it is waging an open, aggressive, bloody and simply beastly full-scale war against us. Destroying civilians, children, schools, kindergartens and all living things around.
Just post #InSupportPalestine or #StandWithPalestine
